### ISSUE TITLE
macOS Ventura

### ISSUE THREAD

**Issue by FidelGB** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#17]
Hi, I'm again, this is not an issue, I'm actually being a backup in time machine of my hackintosh in my Lenovo because I'll try install macOS Ventura and I use this post to write you what works and what doesn't work.

![image](https://user-images.githubusercontent.com/54261598/179375649-71fd650d-e39d-48d7-a5e0-89b60222c46d.png)

**Comment by FidelGB** [comment]
First test. Ir doesn't work 
![image](https://user-images.githubusercontent.com/54261598/179647209-639992b7-07bc-4519-ad94-8a5eacffcdbc.jpeg)

**Comment by seven-of-eleven** [comment]
@FidelGB I've read on Reddit that the latest Ventura beta (3) requires OC-0.8.3. I don't know if that's just people flexing but if you want to test Ventura with the EFI you may want to try an earlier beta version. (Although I'm not sure if you can get an earlier beta.) Either way thanks for testing.

**Comment by alexjaixd** [comment]
Ventura works for now. Still needs some testing to confirm reliability though.
![A17D1BC6-2E01-4C50-A5EE-C3F364DA59E8](https://user-images.githubusercontent.com/86264021/183916677-86af7db3-3aa7-4b72-8f5e-68067c8fc142.jpeg)

**Comment by alexjaixd** [comment]
Everything should just work like in Big Sur / Monterey. Obviously set min/max kernel and use Ventura specific kexts for intel wifi&BT. Pretty smooth experience otherwise.

**Comment by alexjaixd** [comment]
Should add that Ventura at this stage doesn't shut down correctly and gives an KP error upon turning back on again due to VoodooI2CHID.kext being the culprit (has already been mentioned in VoodooI2C's official repo by many others, but apparently devs not focusing on Beta builds yet).  
To fix that, the only way now is to disable the kext from loading in Ventura but that means also losing the touchscreen.

**Comment by seven-of-eleven** [comment]
@alexjaixd thanks for the heads up. I haven't tested the latest Ventura beta on this laptop.

**Comment by FidelGB** [comment]
This last weekend I tried to install Ventura using last version of OpenCore (0.8.5), I have some issues like wifi and bluetooth doesn't work and the laptop restarts every 3 to 5 minutes or so. I realized that the installation doesn't finish because the latopt is restarted and I don't known if this is the cause.

**Comment by seven-of-eleven** [comment]
@FidelGB Thanks for the heads up. I haven't tested the release version with my EFI yet. I had tried an earlier version on an external drive. There is an alpha [AirportItlwm.kext](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0-alpha) available, which is supposed to work with Ventura which you can try. I think bluetooth should work though. If you 're super eager you can try disable the kexts to see if the install completes. Then re-enable them afterwards. I have Ventura installed on another system (without wifi) and intel bluetooth is working well. 

Personally, I plan to wait for the stable AirportItlwm.kext to come out (unless I get really board). So far Ventura doesn't entice with anything I can't live without. If I do install I'll likely first try it on an external drive again.

**Comment by alexjaixd** [comment]
@FidelGB's restarting issue is very likely cause by the VoodooI2CHID problem I mentioned above, I was having restarting issue upon waking up the device. Since your device is a non yoga L13, I would suggest to disable VoodooI2CHID and any related kexts for touchscreen since you wouldn't have any use for that. It should fix the restarting problem. For the wifi to work in Ventura, you'll need alpha version of Airportitlwm, as @seven-of-eleven mentioned. You can set Min & Max kernel like this if you triple boot Big Sur, Monterey & Ventura.
![Screenshot 2022-11-03 at 1 18 13 PM](https://user-images.githubusercontent.com/86264021/199652577-f340c54a-349f-4e40-ac0d-26c97e071fd1.png)

**Comment by alexjaixd** [comment]
@seven-of-eleven As for the VoodooI2CHID problem in Ventura, I think we might actually have an even bigger problem. VoodooI2C devs are coming up with a fix for the Ventura restart KP problem. But I think the new fix will be based on V2.7 of VoodooI2CHID, which is the version that we started having the Wacom AES pen touch problem. 
If this turned out to be the case, we might have to compare the changes commit by commit on what they fixed for the Ventura KP problem and apply them our own for V2.6.5 VoodooI2CHID.

**Comment by FidelGB** [comment]
After long time... AirportItlwm.kext has been released to stable version 2.2.0, so I wait that this release works also with Sonoma, but in this moment is stable for Ventura and Monterey, so @seven-of-eleven can you update the release for this new version of kext please?

**Comment by seven-of-eleven** [comment]
Thanks @FidelGB I'll have sometime this weekend to update.

**Comment by seven-of-eleven** [comment]
@FidelGB EFI has been updated (including AirportItlwm.kext). Note issues with Ventura with VoodooI2C version 2.6.5 kext. You may want to replace those if you upgrade but then you will break pen support. Best.
