### ISSUE TITLE
Freezing on progress bar (booting off USB, not SSD)

### ISSUE THREAD

**Issue by bladehorton** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#23]
Taken all of the bios settings, the OpenCore guide, and your EFI folder (along with generating an SMBIOS) into account, and got the Apple logo up. Makes a small amount of progress then just, reboots back into my currently installed OS. No error message, only black screen then back to the Diagnostic boot screen, and systemd-boot. Tried both Ventura and Monterey, provided by macrecovery as DMG and chunklist files.

The operating systems that I currently have installed are; Windows 10 22H2, and Arch Linux.
Obviously using an L13 Yoga, with an i5

**Comment by seven-of-eleven** [comment]
Sorry for late response on this. Can you turn on the verbose option by adding `-v` to your boot-args. Also do you know what make/modle NVME drive you have installed. MacOS has issues with some of them.

Best

**Comment by bladeperson** [comment]
That's all good. I can try that later today/in a few hours due to me not being at my laptop right now.

The NVME drive appears to be a SKHynix HFS256GD9TNG-L5B0B (long name, I know) and it is the drive that came with my ThinkPad when I bought it

**Comment by bladeperson** [comment]
Can't be specific due to OpenCore not producing a proper log file that I can read, but after I select the USB in the OpenCore menu, the text shows a few errors, then spits out a bunch of stuff that goes by too fast to read before restarting the computer. I saw "secure-boot" in there (which I forgot to re-disable after giving up on this for a bit), but once I did, it did the same thing.

Unless you know how I can generate a log file (I can't find any info on doing that), I can't be any more specific. Sorry! Also, sorry about the late reply, was busy with school.

**Comment by seven-of-eleven** [comment]
You can enable debugging by following [the guide here](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps). That should provide a log file on you EFI partition and additional information during boot.

If you have an external drive available it may be worth while to try and install on it first to see if it is your SKHynix drive causing the problem?

Do you know if you're using a USB 2 or USB 3 key for the install? Some reported issues with USB 3.

**Comment by bladeperson** [comment]
Okay, thanks. I'll enable debugging and get back to you with a log file. For now, I can't install to anything because I can't get into the installer in the first place, though once I do I will certainly try to install to an external drive.

As for the USB, It is USB 3, and I have tried a USB 2 drive before, and it made no difference to the results. I can try again if you wish, but as far as I know, it doesn't help

**Comment by bladeperson** [comment]
Here we go, There's the log file.


[opencore-2023-06-01-090502.txt](https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/files/11623219/opencore-2023-06-01-090502.txt)

**Comment by seven-of-eleven** [comment]
Try replace your config.plist file with the one attached. You will have to update the serial numbers in the PlatformInfo section.

[config.plist.zip](https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/files/11697400/config.plist.zip)

**Comment by bladeperson** [comment]
No visible difference when booting.

New Log File here: 
[opencore-2023-06-01-085909.txt](https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/files/11712394/opencore-2023-06-01-085909.txt)

**Comment by seven-of-eleven** [comment]
Hi @bladehorton I just updated the EFI folder to OC-0.9.3. If you still have issues installing, try changing the SecureBootModel value to `Default` instead of the `j223` that I have it set to in the config. You can always change it back to j223 afterwards. Your Log file shows "07:625 02:108 OC: Loading Apple Secure Boot with j223 (level 1)" it looks like it was still set to j223. Not sure if that will help, it's been a long time since I did the install. I also just tested booting Ventura from an external drive with the 0.9.3 EFI and it worked.

**Comment by bladeperson** [comment]
Yeah, no difference. The new EFI folder (whith the serial numbers i previously generated copied over) did not make any visual changes. Neither did using the new folder while changing SecureBootModel to default.

**Comment by bladeperson** [comment]
Hi @seven-of-eleven 
Any updates? I can't see anything in the log file that would cause it to freak out and crash personally. I have tried on and off for a little bit since writing my last comment, but nothing has changed

**Comment by seven-of-eleven** [comment]
Hi @bladehorton I don't see anything that would cause an issue. I'm wondering if it is related to the Multiple OSs you're running. I don't multi-boot so I can't really help in this area. You can review the [Opencore Multiboot guide](https://dortania.github.io/OpenCore-Multiboot/). It may have some tips for you. Alternatively I would try install on an external drive to see if that works.

Can you provide an updated log file?

**Comment by bladeperson** [comment]
I cannot provide an updated log file as my previous attempts after making my comment on June 17th have been using the Stable build, which while less useful for troubleshooting it is more stable and I thought it could help. Thankfully I am getting a new laptop this afternoon, and once I have cloned my Linux installation onto the new SSD, we won't have to worry about multibooting, as my ThinkPad will remain blank until we get the MacOS installation disk booting

**Comment by bladeperson** [comment]
Hello again,
It's been a little bit since I've revised this issue, for a while I've been working on my new computer and my L13 Yoga has been left blank for some time. I started over again, and used your EFI folder, and this time tried to use Big Sur, instead of Montery or Ventura. Still no luck. Awaiting on some kind of fix still, or something to pop up to me in a log file perhaps. But for now, I'm still stuck.

**Comment by seven-of-eleven** [comment]
I haven't included all the kexts for Big Sur so it likely wouldn't work 100%. Monterey or Ventura should work without issue. 

I'll be updating the EFI to the latest over the next week and including Sonoma support. You're welcome to try again at that point. Without logs/errors it's hard to trouble shoot. Everything works on my end and the only change I make to the EFI uploaded here is removing the serial numbers.

Best

**Comment by bladeperson** [comment]
I've tried the latest EFI folder upload, even without any changes and with a Sonoma partition on my USB (I followed the "Making the installer in Linux, Method 2) and it seems to have gotten worse? The progress bar does not even show up anymore. Out of curiosity, would you be able to provide a disk image of your USB stick that you used to install macOS? If so, I could flash that image onto a USB stick and try it again. If you can get an installation disk running with Sonoma and the EFI folder provided in the releases of this GitHub repo (meaning, still lacking serial numbers). In short, get a disk image of your working install USB, and try it myself. Sorry for taking so long by the way, I've been extremely busy

**Comment by bladeperson** [comment]
Actually, here's an extra question I probably should have asked ages ago. Are you running this on a generation 2 or 3 L13 Yoga? My current system is only a generation 1, and I'm not sure if that would cause any problems when running something meant for a gen 2, but maybe a gen 3
